### PR TITLE
Create a collapse button for all racks

### LINKED ISSUE #93: Add a "Collapse rack" button on all racks
As a user, I want to be able to hide/show the contents of a rack to make some space for other racks, for example.

Technical details:
- The button should optimally unload/load the rack contents through a Loader object, in QML.
- An animated transition is not mandatory, but can be considered and explored.

### PR DESCRIPTION
**Pull request by lucidism**
This PR closes #93.

A new button was added to the right of all rack label areas. When the rack is fully expanded, on interaction, it will narrow down the rack content's visible area to 0, effectively hiding it from the viewport. In that state, only the rack label should be visible. Inversely, re-clicking on the button when the rack is "collapsed" will restore its height back to where it was prior to initial interaction. Since the collapse state is implemented as a `Rack` property, certain racks can be initialized to a collapsed state on generator selection. By default, this value is set to false.

Screenshot_2

A quick note for the future: while the current solution is functional, it is far from optimal, since the rack contents are collapsed using the clipping method, and never unloaded once collapsed. As a result, potentially unnecessary rendering power is needed when rack contents aren't visible. This will require further investigation. [More info on the effect of clipping on performances here.](https://doc.qt.io/qt-5/qtquick-performance.html#clipping)

### CODE REVIEW

**Comment by lucidism** [comment]
@simondemeule I actually added the rack button icons as SVGs initially, but I decided to convert them into PNGs because of a dumb bug that involves subpixel rendering. for some reason, `icon-collapse.svg`'s arrowhead was semi-precisely rendered, and it would look even worse in its `pressed` state: the arrowhead was barely even visible thanks to `ColorOverlay`, which inverts the icon's color when `pressed`. using PNGs turned out to alleviate this issue with an acceptable margin of error, but I do agree that SVGs would be overall better suited for this type of UI spec. I'll try and see if I can at least use two color variations per icon, which would result in 4 different SVG files, and adapt the state logic consequently, or if I can throw in a custom color overlay shader. as for the light cue asset, I'll apply changes right away :-)

**Comment by simondemeule** [comment]
@lucidism it looks like the bad SVG rendering is caused by a bug in QML's `Image` object's SVG rendering that is specific to HiDPI screens. I've [found a bug report](https://bugreports.qt.io/browse/QTBUG-58416) on Qt's issue tracker that describes a workaround for this, which requires rendering the SVG on the C++ side, and then sending that image to Qt. [This stackoverflow thread](https://stackoverflow.com/questions/37976644/how-to-make-svg-icons-crisp-again-in-qt-5-6-on-high-dpi-screens) describes a much simpler fix done in QML only, but I couldn't get it to work properly. I don't know much about how QML works, so maybe you would have a better shot at trying to get it to work?

I've also tried all combinations of `smooth` and `mipmap` properties, and no combination of antialiasing settings leads to good result. 
- Setting `smooth: false`, `mipmap: false` leads to the rendering happening at a low resolution, with no smoothing applied afterwards, leading to very harsh pixellation.  
- Setting any other combination of `smooth` and `mipmap` properties leads to the rendering happening at a low resolution, with smoothing applied at high resolution, leading to very odd and unsharp looking icons.  

I've also tried expanding the stroke of the SVG in illustrator, so that it is rendered as a filled closed path, and it doesn't seem to help.

I suggest we go ahead with the pull request and create a new issue to fix this in a future pull request. In the worst case if we don't manage to implement the fix we can revert back to PNG later.

**Comment by simondemeule** [comment]
@lucidism just an extra thought: in the mean time we might want to stick to `smooth: true`, `mipmap: false`, as it seemed to be the least ugly of the bunch.

**Comment by simondemeule** [comment]
@lucidism also just realized there seems to be a shader compile error in the debug:

`QOpenGLShader::link: ERROR: Input of fragment shader 'qt_TexCoord0' differs in type/qualifiers to that written by vertex shader
ERROR: Input of fragment shader 'qt_TexCoord0' not written by vertex shader

shader compilation failed: 
"ERROR: Input of fragment shader 'qt_TexCoord0' differs in type/qualifiers to that written by vertex shader\nERROR: Input of fragment shader 'qt_TexCoord0' not written by vertex shader\n"
QOpenGLShader::link: ERROR: Input of fragment shader 'qt_TexCoord0' differs in type/qualifiers to that written by vertex shader
ERROR: Input of fragment shader 'qt_TexCoord0' not written by vertex shader`

**Pull request merged**
