### PR TITLE
Fix random crashes and implement proper threading architecture

### PR DESCRIPTION
**Pull request by simondemeule**
This resolves random crashes (#88) and implements a proper threading architecture by moving the Generator objects and the ComputeEngine to their own thread, and by creating Facade objects belonging to the GUI thread that QML can interact with, which are linked to the Generator objects through signals. The Facade design uses the meta-object system to automatically create QProperties that matches that of the QObject it represents, meaning there is no manual code duplication required when we add more Generator types or other settings-related objects in the future.

### CODE REVIEW

**Comment by simondemeule** [comment]
Also let's stick to rebase when we introduce this into dev

**Comment by simondemeule** [comment]
It looks like some commits are duplicated, I must have messed up the rebase

**Comment by lucidism** [comment]
@simondemeule yeah, I had a similar experience with #83. not really sure if this has to do with the git rebase flow order or just merge conflicts, though

**Comment by simondemeule** [comment]
Reverted back to before it broke, I'll rebase again and hopefully it works. I think I broke it by not force pushing the rebase, and adding a commit on top of it before pushing. Not sure but we'll see.

**Comment by simondemeule** [comment]
The history seems good now, but I either broke (or haven't previously fixed) NeuronType not registering for Facade-Generator signals

**Comment by simondemeule** [comment]
Nevermind that! Just cleaned my build and things are good.

**Pull request merged**
