### PR TITLE
Create a "Lattice" view

### LINKED ISSUE #76: Draw a 2D matrix from the generator in the window
Draw a 2D matrix from the generator in the window.

- Get the data from C++.
- Draw it in an optimized way.

Details:

- Let's use probably a QImage, for now.
- One day, we might want to use shaders.
- Draw a QImage in a Canvas. (or draw an image directly) We can use Canvas::loadImage(image) https://doc.qt.io/qt-5/qml-qtquick-canvas.html

Edit: Draw the matrix in C++ and provide it to QML.

### PR DESCRIPTION
**Pull request by lucidism**
This PR closes #76.

A new page, dubbed "Lattice View", has been added to the application, in parallel to the already established Generator View. It can currently be accessed by using the Ctrl+L shortcut on Windows.

ezgif com-video-to-gif

In this first iteration of the Lattice view, this PR includes:
- **basic UI** for information display (the active generator's name) and navigation (for going back to the Generator View);
- a rudimentary **neuron matrix shader file** that takes an image (the mapped neuron grid generated from C++) as input, upscales it to a fixed size (here, 400px by 400px), centers it in the container area and applies padding (in this case, 3px around) on each "neuron";
- a `Canvas` object that **non-interactively draws input/output zones** on the aforementioned neuron matrix from two given `QRect` arrays, both of which will eventually be served through C++;
- a thorough **front-end folder restructure/refactor**: folder names are now uniformly lowercased and QML files have been properly reorganized into a semantically appropriate structure.

Some known bugs relative to display quality have not been addressed yet; for instance, the shader code currently displays diagonal splice artifacts when the container width is odd-numbered, and subpixel rendering differences between GLSL and Canvas are both visible and unprecise. Furthermore, all preliminary tests were done with a static 20x20 .png grid, and thus, any other neuron grid resolution is not guaranteed to properly work.

### CODE REVIEW

**Comment by simondemeule** [comment]
@lucidism At the moment I am getting a shader compile error on macOS. I can't debug it or really go through the whole review at the moment but I'll give it a shot later tonight.

Capture d’écran, le 2020-07-15 à 20 03 29

QOpenGLShader::compile(Fragment): ERROR: 0:10: '*' does not operate on 'vec2' and 'int'
ERROR: 0:10: '/' does not operate on 'float' and 'int'
ERROR: 0:11: Use of undeclared identifier 'st'

*** Problematic Fragment shader source code ***
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#define lowp
#define mediump
#define highp
#line 1
uniform sampler2D textureMap;
varying vec4 qt_TexCoord0;

uniform int imgWidth;
uniform int imgHeight;

void main(void)
{
    vec2 st = floor(qt_TexCoord0.xy * imgWidth) / imgWidth + (0.5 / imgWidth);
    gl_FragColor = texture2D(textureMap, st);
}

***
QQuickCustomMaterialShader: Shader compilation failed:
"ERROR: 0:10: '*' does not operate on 'vec2' and 'int'\nERROR: 0:10: '/' does not operate on 'float' and 'int'\nERROR: 0:11: Use of undeclared identifier 'st'\n"

**Comment by lucidism** [comment]
@simondemeule dumb question, but did you pull the branch on your local system? this looks like a really early version of `neuron_matrix.frag`, this is what the code should _technically_ look like in its current state:
Screenshot_4
otherwise, you might just need to clean your build; maybe that has something to do with it.

**Comment by simondemeule** [comment]
I’m away from my computer but it seems that could be the issue — the shader that was causing problems was only about 10 lines. Something might have gone wrong with git on my side.

**Comment by lucidism** [comment]
@simondemeule agreed! I actually had a header planned in the Generator View mockups, so using that area as a link with the Lattice View is definitely a reasonable idea. I'll do some design prototyping on my end to see what works best. might end up changing some things to the original design in the process, since the header zone will most likely cover more functionalities than originally planned.

**Comment by simondemeule** [comment]
@lucidism also, just a last minute thought: the same way there is a message when nothing is selected in the lattice view, we could have a similar message on the default view.

**Comment by simondemeule** [comment]
@lucidism yet another thought: if the default and lattice view are going to be the two main pages the user interacts with, and switching between the two is frequent, maybe we could do just like in Ableton does with session and arrangement views, and set the key-binding for that to TAB, since that is much easier to reach than CMD+L?

**Pull request merged**
